name = "XKeyboard"
uuid = "0c8a7d74-93ea-4f23-9ed1-b26578bfdfe6"
authors = ["Cédric BELMANT"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
